# based on: https://anasdidi.dev/articles/200713-docker-compose-postgres/
volumes:
  devops_postgres:
  devops_pgadmin:

networks:
  devops_postgres:
    external: false

services:
  postgres:
    image: postgres:16
    container_name: devops_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XX21fgwkoMZ4Bu74
    networks:
      - devops_postgres
    volumes:
      - devops_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: devops_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: helpdesk@devops.tech
      PGADMIN_DEFAULT_PASSWORD: iKSYN1Uuz8DxEmoz
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - devops_pgadmin:/var/lib/pgadmin
    networks:
      - devops_postgres
    depends_on:
      - postgres



