# Generated by Django 4.2.4 on 2024-10-06 17:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=100)),
                ('genus', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('formed', 'сформирован'), ('completed', 'завершён'), ('cancelled', 'откланен'), ('deleted', 'удален')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 6, 20, 54, 13, 468157))),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'animals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'действует'), ('deleted', 'удален')], default='active', max_length=15)),
                ('picture_url', models.URLField()),
                ('description_picture_url', models.URLField()),
            ],
            options={
                'db_table': 'habitats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HabitatAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_habitats', to='animals.animal')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.habitat')),
            ],
            options={
                'db_table': 'habitats_animals',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='habitatanimal',
            constraint=models.UniqueConstraint(fields=('habitat', 'animal'), name='unique_habitat_animal'),
        ),
    ]
