# Generated by Django 4.2.4 on 2024-10-07 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='final_population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 24, 4, 764668)),
        ),
    ]
