# Generated by Django 4.2.4 on 2024-10-09 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_final_population_alter_animal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 9, 11, 54, 38, 135307)),
        ),
    ]
