# Generated by Django 4.2.4 on 2024-10-12 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0005_alter_animal_created_at_alter_animal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 12, 57, 50, 175385)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
